syntax = "CfxLua"
indent_type = "Spaces"
indent_width = 2
call_parentheses = "None"
no_call_parentheses = true
quote_style = "ForceSingle"
collapse_simple_statement = "ConditionalOnly" 
[sort_requires]
enabled = true
